#!/usr/bin/env python3
"""Deterministically generate Codex TOML agents from Markdown sources."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "agents-src"
OUTPUT_DIR = ROOT / "agents"
EXPECTED = (
    "blog-brain-curator",
    "blog-researcher",
    "blog-reviewer",
    "blog-seo",
    "blog-translator",
    "blog-writer",
)
KEY_RE = re.compile(r"^([a-z_]+):(?:\s*(.*))?$")


def parse_source(path: Path) -> tuple[dict[str, object], str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: missing frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError(f"{path}: unterminated frontmatter") from exc

    header = lines[1:end]
    values: dict[str, object] = {}
    index = 0
    while index < len(header):
        match = KEY_RE.match(header[index])
        if not match:
            raise ValueError(f"{path}: invalid frontmatter line {index + 2}")
        key, raw = match.groups()
        raw = raw or ""
        if raw in {">", "|"}:
            index += 1
            parts: list[str] = []
            while index < len(header) and header[index].startswith("  "):
                parts.append(header[index].strip())
                index += 1
            values[key] = " ".join(parts) if raw == ">" else "\n".join(parts)
            continue
        if raw == "":
            index += 1
            items: list[str] = []
            while index < len(header) and header[index].startswith("  - "):
                items.append(header[index][4:].strip())
                index += 1
            values[key] = items
            continue
        values[key] = raw.strip().strip('"')
        index += 1

    body = "\n".join(lines[end + 1 :]).strip() + "\n"
    return values, body


def render_agent(name: str) -> str:
    source = SOURCE_DIR / f"{name}.md"
    values, body = parse_source(source)
    if values.get("name") != name:
        raise ValueError(f"{source}: frontmatter name must be {name!r}")
    description = values.get("description")
    nicknames = values.get("nickname_candidates")
    if not isinstance(description, str) or not description:
        raise ValueError(f"{source}: description is required")
    if not isinstance(nicknames, list) or not nicknames:
        raise ValueError(f"{source}: nickname_candidates must be a non-empty list")

    generated = (
        "# Generated by scripts/generate_agents.py; edit agents-src instead.\n"
        f"description = {json.dumps(description, ensure_ascii=False)}\n"
        f"nickname_candidates = {json.dumps(nicknames, ensure_ascii=False)}\n"
        f"developer_instructions = {json.dumps(body, ensure_ascii=False)}\n"
    )
    return generated


def expected_outputs() -> dict[Path, str]:
    return {OUTPUT_DIR / f"{name}.toml": render_agent(name) for name in EXPECTED}


def check(outputs: dict[Path, str]) -> int:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"stale: {path.relative_to(ROOT)}")

    expected_paths = set(outputs)
    if OUTPUT_DIR.exists():
        for path in sorted(OUTPUT_DIR.glob("*.toml")):
            if path not in expected_paths:
                failures.append(f"unexpected: {path.relative_to(ROOT)}")

    if failures:
        print("Agent generation check failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1
    print(f"Agent generation check passed ({len(outputs)} agents).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated agents are missing or stale")
    args = parser.parse_args()

    outputs = expected_outputs()
    if args.check:
        return check(outputs)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
